Changed list to dictionary for Quotes
Vyvy-vi/TearDrops pull request #101
Opened 2020-11-07 05:47 UTC by LazybuddyNK

Is this fine, if not please tell.

2020-11-07 17:36 UTC, Vyvy-vi requested changes

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +       "Any sufficiently advanced technology is indistinguishable from magic." : " Arthur C. Clarke",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +       "The only way of discovering the limits of the possible is to venture a little past them into the impossible."     :" Arthur C. Clarke",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +       " You cannot depend on your eyes when your imagination is out of focus."      :" Mark Twain",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +       " You cannot depend on your eyes when your imagination is out of focus."      :" Mark Twain",
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +       "How wonderful that we have met with paradox. Now we have some hope for making progress."   :"  NEILS BOHR",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "I canna’ change the laws of physics, Captain!"       :" SCOTTY, CHIEF ENGINEER IN STAR TREK",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "I canna’ change the laws of physics, Captain!"       :" SCOTTY, CHIEF ENGINEER IN STAR TREK",
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "Only those who attempt the absurd will achieve the impossible."   :" JOHN WHEELER",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "Only those who attempt the absurd will achieve the impossible."   :" JOHN WHEELER",
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "Someday in the next thirty years, very quietly one day we will cease to be the brightest things on Earth."         :" JAMES McAlear",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "Someday in the next thirty years, very quietly one day we will cease to be the brightest things on Earth."         :" JAMES McAlear",
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "- Either we are alone in the universe, or we are not. Either thought is frightening."       :" ARTHUR C. CLARKE",
extra whitespace around ':'
should be like this--> {"key": "value"}

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "- Either we are alone in the universe, or we are not. Either thought is frightening."       :" ARTHUR C. CLARKE",
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "'listen: there’s a hell of a good universe next door; let’s go"           :" E. E. CUMMINGS",
extra whitespace around ':'
should be like this--> {"key": "value")
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "Get busy living or get busy dying."           :"Stephen King",
extra whitespace around ':'
should be like this--> {"key": "value")
Extra ' ' before name--> looks weird on print.

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "**Never** trust a **hug**.It's just a way to hide your face..."           :""",
extra whitespace around ':'
should be like this--> {"key": "value")
Three quote marks in value field

2020-11-07 17:36 UTC, Vyvy-vi commented on bot/inputs.py
> +        "I want you to know that someone cares. Someone, not me           :"",
should be like this--> {"key": "value")
Missing `"` in key

2020-11-07 19:59 UTC, Vyvy-vi commented
regarding #100

2020-11-07 21:52 UTC, Vyvy-vi approved these changes

2020-11-07 21:53 UTC, merged

2020-11-07 22:29 UTC, Vyvy-vi commented
Could have been better
I would call this work slightly untidy, but here's a suggestion: try using pylint/flake8 code linters before making a commit.
👍 
Or try: https://shorturl.at/ajsLS

2020-11-07 22:31 UTC, Vyvy-vi commented
@all-contributors add @LazybuddyNK for docs

2020-11-07 22:55 UTC, Vyvy-vi commented
oh wupps

2020-11-07 22:55 UTC, Vyvy-vi commented
@all-contributors add @LazybuddyNK for code

2020-11-08 06:21 UTC, LazybuddyNK commented
> Could have been better
> I would call this work slightly untidy, but here's a suggestion: try using pylint/flake8 code linters before making a commit.
> 👍
> Or try: https://shorturl.at/ajsLS

Thanku for suggestion, I wasn't even knowing about it.
And yes it's very helpful.

Really Thank you again, that's why I have started getting involved in open source.