Dockerize the app.
Vyvy-vi/TearDrops pull request #76
Opened 2020-11-01 15:35 UTC by anubhavcodes

This commit introduces multiple new concepts and features.

1. The bot is now running inside a docker container.
2. The whole project can be run using on command
   `docker-compose up -d`
3. No need to share one test database for all users running the bot locally on their machines.
4. Delete `setup.py`, as it was not used in the right sprit of python.
5. Use .env to inject `DISCORD_BOT_TOKEN`.

@Vyvy-vi I imagine you will have lot of questions, and please feel free to ask them, I will be very happy to explain it to them. Docker is a pretty cool technology, but at the same time, can take a bit of time to wrap your head around it which is totally fine. 

Don't merge it right away as it might break production. We should check if the `MONGO_CONNECTION_STRING` is working for the production string. 

You can test this locally by pulling the changes locally in a separate branch and running. 

```
docker-compose up -d
```

2020-11-01 15:42 UTC, sayand0122 requested changes
I suggested the use of .env before to @Vyvy-vi but its ok now

2020-11-01 15:43 UTC, sayand0122 reviewed
@anubhavcodes do you mind like teaching how to dockerize... U can do so in the discord server... I am present in that server as Duke

2020-11-01 20:20 UTC, Vyvy-vi commented
Initially I was using env vars but switched to a setup.py file as some contributors were not able to set up env vars in windows.
though using .env as @sayand0122 suggested is a better fix 👍

2020-11-01 20:31 UTC, Vyvy-vi commented on .gitignore
> +
approved.
.env needs to be in .gitignore as this might contain sensitive data for the bot (token)

2020-11-01 20:31 UTC, Vyvy-vi commented on bot/Dockerfile
> +FROM python:3.8-slim
that's the python builder for docker, right?

2020-11-01 20:31 UTC, Vyvy-vi commented on README.md
> +docker-compose up
maybe add a link to docker(some contribs. might not know about it)

2020-11-01 20:31 UTC, Vyvy-vi commented on bot/main.py
> +MONGO_CONNECTION_STRING = get_environment_variable("MONGO_CONNECTION_STRING")
Better than using the seperated env-variables 👍

2020-11-01 20:31 UTC, Vyvy-vi commented on bot/main.py
> +MONGO_CONNECTION_STRING = get_environment_variable("MONGO_CONNECTION_STRING")
I planned on making it in one URi, but forgot

2020-11-01 20:31 UTC, Vyvy-vi commented on bot/main.py
> +DB_CLIENT = MongoClient(MONGO_CONNECTION_STRING)
this ports mongo through docker container?

2020-11-01 20:31 UTC, Vyvy-vi commented on bot/utils.py
> +        return coerce(value)
does this force data types to become similar?

2020-11-01 20:31 UTC, Vyvy-vi commented
I'm going to reproduce your version locally to check 👍

2020-11-01 21:58 UTC, Vyvy-vi commented on README.md
> +docker-compose up
Maybe add how to put the bot down
```
docker-compose down
```

2020-11-01 21:58 UTC, Vyvy-vi commented on bot/Dockerfile
> +FROM python:3.8-slim
So, this creates a docker container for every bot hosted(different tokens)
There was a server sync issue(the alternate-bots didn't connected to the db in their runtime only)
After termination, the data wasn't stored.
Would this happen for the main bot as well?
We need to store the data on there even if the bot goes down so that we can use the previously stored values. 
this is at 3:11-->
![Screenshot 2020-11-02 at 3 26 31 AM](https://user-images.githubusercontent.com/62864373/97816441-4ced1500-1cbb-11eb-8e99-0c1af033e65b.png)
after a few mins, after a rerun-->
![Screenshot 2020-11-02 at 3 26 42 AM](https://user-images.githubusercontent.com/62864373/97816448-642c0280-1cbb-11eb-8682-1912faaa62e9.png)

the db resets on termination/....

2020-11-02 06:14 UTC, Vyvy-vi approved these changes

2020-11-02 09:44 UTC, anubhavcodes commented on bot/Dockerfile
> +FROM python:3.8-slim
Hi, to answer you questions: 

1. `FROM python:3.8-slim` is the base image that we use, and our own custom image for the bot-server will use it. You can read more about it [here](https://stackoverflow.com/a/33836848)

2. Regarding the db reset on termination. Yes, when you do `docker-compose down` all your containers (that were created from images/services in `docker-compose.yml` ) will be deleted. And that's fine as long as it's local setup. 

We want to be able to let our developers be able to write and test their code and `docker-compose up` helps them do just that. But we won't be deploying this via `docker-compose` in production. 

For production you have two options: 

- You leave everything as is at the moment, and it will still work. You just have to change the environment variables in your Heroku app settings and add a `MONGO_CONNECTION_STRING` with the correct string for production. Your app will pick it up and start logging to the mongo that you have running in production. This database will never be deleted unless you delete it yourself. 

- Or you can change the way your code is running in production by running your production server code in a docker container. At the moment you don't have to do this, but one day when your users increase and you start raking up bills, this will make more sense.

2020-11-02 09:48 UTC, anubhavcodes commented on README.md
> +docker-compose up
Yes, will do that. 

Regarding steps to clean the containers: 

You can do `docker-compose stop` to just stop the containers. In this case, your containers won't be deleted and also the data between them. 

You can also do `docker-compose down` to just clean up everything.

2020-11-02 09:53 UTC, anubhavcodes commented on README.md
> +docker-compose up
This is done. you can resolve this if you want.

2020-11-02 09:56 UTC, anubhavcodes commented on bot/main.py
> +MONGO_CONNECTION_STRING = get_environment_variable("MONGO_CONNECTION_STRING")
You mean for local setup right, that's okay, because `docker-compose` creates a new container. You can see it in `docker-compose.yml` as : 

```yml
services:
  db:
    image: mongo:3.6.20
```

And you can see how your bot is connecting to this mongo using: 

```yml 
  bot:
    build:
      context: bot
    environment:
      MONGO_CONNECTION_STRING: "mongodb://db:27017"
      DISCORD_BOT_TOKEN: #will be injected via .env
...
...
```

Here is you change the `MONGO_CONNECTION_STRING` to the one from before, it will work as your app will then connect to the test database running somewhere else. However it's not a good practise to have every developer connect to one database, rather they should be able to run their on DB locally and test with it ( like how it is with the local mongo that docker is creating for you. )

2020-11-02 10:01 UTC, anubhavcodes commented on bot/main.py
> +DB_CLIENT = MongoClient(MONGO_CONNECTION_STRING)
here you pass the `MONGO_CONNECTION_STRING` ( which is set to `"mongodb://db:27017"`  in the `docker-compose.yml` ) . This will connect your app to the mongo running locally. 

Depending on what is the MONGO_CONNECTION_STRING, your app will connect to the mongo instance accordingly.

2020-11-02 10:02 UTC, anubhavcodes commented on bot/utils.py
> +        return coerce(value)
You can do something like: 

`get_environment_variable("MONGO_PORT", coerce=int, default=27017)`

This will grab the environment variable, get it's value (default to str) and convert into int and return it to you. You don't have to do it yourself.

2020-11-02 18:05 UTC, Vyvy-vi commented on bot/Dockerfile
> +FROM python:3.8-slim
Okay will try modify heroku env-vars for now.

2020-11-02 18:07 UTC, Vyvy-vi commented on bot/main.py
> +MONGO_CONNECTION_STRING = get_environment_variable("MONGO_CONNECTION_STRING")
👍

2020-11-02 18:12 UTC, Vyvy-vi approved these changes

2020-11-02 18:12 UTC, merged

2020-11-02 18:13 UTC, Vyvy-vi commented
I'll merge it and deploy it on heroku to test 👍

2020-11-02 22:00 UTC, anubhavcodes commented
Keep an eye on your mongo connection string and set it properly in your settings in heroku. 

All the best.

2020-11-03 00:02 UTC, Vyvy-vi commented
@all-contributors add @anubhavcodes Infrastructure https://github.com/Vyvy-vi/TearDrops/blob/main/docker-compose.yml